[package]
name = "sing"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26.0"
dirs = "4.0.0"
fs_extra = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.7.1", features = ["preserve_order"] }
